"""empty message

Revision ID: b30dec96abd3
Revises: ca6c2cbc554d
Create Date: 2020-05-07 23:12:16.365159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b30dec96abd3'
down_revision = 'ca6c2cbc554d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    print("good upgrade")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('restaurants')
    # ### end Alembic commands ###
